# Projects Configuration File
# Add your projects here with just the essential information

[[projects]]
name = "NetGuardian"
description = "NetGuardian integrates an AI-powered detector to inspect incoming HTTP requests in real time, pinpoint exploitable parameters, and emit alerts. This post explains every part of the detector.py service, provides the requested ASCII flowchart, and shows how to integrate it with your C++ proxy."
category = "AI & Security"
icon = "🤖"
link = "https://github.com/abode1234/network-guardian"
technologies = ["Python", "TensorFlow", "PyTorch", "c++", "XGBoost", "porxy broker"]
highlights = [
    "ML model with 94% accuracy in vulnerability prediction",
    "Automated scanning with intelligent prioritization",
    "Real-time threat intelligence integration"
    " 1. Extracts 80 features from each HTTP request in real time.
2. Runs XGBoost inference to detect malicious payloads.
3. Uses SHAP to identify the most suspect parameter in each request.
4. Returns JSON indicating `allow`/`block`, probability, and `vulnerable_param`.
5. Optionally webhooks alerts to Slack/Teams/other systems."
]


